---
title: "Pipeline to assess cell and gene scores distributions for selections via geneBasis (melanoma)."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---
# Load dependencies

```{r load, message = FALSE}


library(SingleCellExperiment)
library(batchelor)
library(stats)
library(BiocNeighbors)
library(tibble)
library(reshape2)
library(plyr)
library(dplyr)
library(scran)
library(batchelor)
library(stringr)
library(corrplot)
library(ggcorrplot)
library(viridis)
library(wesanderson)

root.dir = "/Users/alsu/Develop/geneBasis/"
source(paste0(root.dir, "am_geneBasis/functions/main_functions.R"))
source(paste0(root.dir, "am_geneBasis/functions/visualization_functions.R"))

system = "melanoma"
sce = readRDS(paste0(root.dir , "data/scRNA_datasets/" , system , "/sce_" , system , ".Rds"))
figures.dir = paste0(root.dir , "figures/benchmark/" , system, "_unbatched/")

# get stat

## cell score
stat_cell_score.scmer_batched = readRDS(paste0(root.dir , "data/benchmark/cell_score/" , system , "_unbatched/cell_score__scmer_batched.Rds"))
stat_cell_score.scmer_unbatched = readRDS(paste0(root.dir , "data/benchmark/cell_score/" , system , "_unbatched/cell_score__scmer_unbatched.Rds"))
stat_cell_score.scgenefit = readRDS(paste0(root.dir , "data/benchmark/cell_score/" , system , "_unbatched/cell_score__scgenefit.Rds"))

## gene score
stat_gene_score.scmer_batched = readRDS(paste0(root.dir , "data/benchmark/gene_score/" , system , "_unbatched/gene_score__scmer_batched.Rds"))
stat_gene_score.scmer_unbatched = readRDS(paste0(root.dir , "data/benchmark/gene_score/" , system , "_unbatched/gene_score__scmer_unbatched.Rds"))
stat_gene_score.scgenefit = readRDS(paste0(root.dir , "data/benchmark/gene_score/" , system , "_unbatched/gene_score__scgenefit.Rds"))

# just my selection - for saturation analysis
stat_cell_score.alsu = stat_cell_score.scgenefit[stat_cell_score.scgenefit$type == "geneBasis" & stat_cell_score.scgenefit$nPC == "all", ]
stat_gene_score.alsu = stat_gene_score.scgenefit[stat_gene_score.scgenefit$type == "geneBasis" & stat_gene_score.scgenefit$nPC == "all", ]



```

# Set up color schemes

```{r color-schemes, message = FALSE}


pals1 = wes_palette("Darjeeling1", n = 5)
pals2 = wes_palette("Darjeeling2", n = 5)
pals3 = wes_palette("Royal1", n = 4)
pals4 = wes_palette("Royal2", n = 5)

type_cols = c("geneBasis" = pals3[2] , "scgenefit" = pals1[3] , "SCMER" = pals1[5] , "hvgs" = pals1[3] )
  
celltype_cols = celltype_colors[[which( names(celltype_colors) == system )]]


```


# Supp figures

## A: cell score lower than thresh - heatmap (geneBasis)

```{r cell-score-lower-than-thresh, message = FALSE}


n_genes.grid = c(30, 70 ,110,150)
cell_score.grid = c(0 , 0.25 , 0.5, 0.75)

stat_cell_score = lapply(n_genes.grid , function(n_genes){
  print(n_genes)
  stat_per_n_genes = lapply(cell_score.grid , function(cell_score){
    current.stat = stat_cell_score.alsu[stat_cell_score.alsu$n_genes == n_genes & stat_cell_score.alsu$score < cell_score , ]
    out = data.frame(n_genes = n_genes , cell_score = cell_score , n_below = nrow(current.stat)/nrow(stat_cell_score.alsu))
    return(out)
  })
  stat_per_n_genes = do.call(rbind , stat_per_n_genes)
  return(stat_per_n_genes)
})
stat_cell_score = do.call(rbind, stat_cell_score)


p1 = ggplot(stat_cell_score, aes(x = factor(n_genes) , y = factor(cell_score) , fill = log(n_below))) + 
  geom_tile(aes(fill = log(n_below))) + 
  geom_text(aes(label = round(n_below,4)) , color = "red", size = 4) +
  scale_fill_viridis(discrete = F) + 
  theme_classic() +
  labs(x = "# genes selected" , y = "Cell score threshold") + 
  guides(fill=guide_legend(title="ln(# cells)"))
p1
ggsave(filename = paste0(figures.dir , "lowly_explained_cells/", "heatmap_stat" , ".png"), plot = p1, width = 4, height = 3)


```

## B: gene score boxplot (geneBasis VS SCMER)

```{r gene-score-boxplots, message = FALSE}



get_gene_score_plot = function(stat, nPC, corr_all.thresh = .25){
  p = ggplot(stat[stat$nPC == nPC & stat$corr_all >= corr_all.thresh, ] , aes(x = factor(n_genes)  , y = corr_ratio, fill = type)) + 
    geom_boxplot() + 
    scale_fill_manual(values = type_cols) + 
    theme_classic() + 
    labs(y = "" , x = "") +
    ylim(c(0,1)) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) + 
    theme(legend.position = "none")
  return(p)
}


p = get_gene_score_plot(stat_gene_score.scmer_batched[stat_gene_score.scmer_batched$type %in% c("geneBasis" , "SCMER") , ] , "all") +         ggtitle("Gene prediction")
p
ggsave(filename = paste0(figures.dir , "gene_score_distr" , ".png"), plot = p, width = 4, height = 2)


```

## C: gene score lower than thresh - heatmap (geneBasis)

```{r gene-score-lowly-expressed-genes, message = FALSE}


n_genes.grid = c(30, 70 ,110,150)
corr_ratio.grid = seq(0.25 , 0.75 , 0.1)
corr_ratio_all.thresh = 0.25

stat_coexpression = lapply(n_genes.grid , function(n_genes){
  stat_per_n_genes = lapply(corr_ratio.grid , function(corr_ratio){
    current.genes = as.character( stat_gene_score.alsu$gene[stat_gene_score.alsu$n_genes == n_genes & stat_gene_score.alsu$corr_ratio <= corr_ratio & stat_gene_score.alsu$corr_all > corr_ratio_all.thresh] ) 
    if (length(current.genes) > 1){
      current.sce = sce[current.genes , ]
      current.counts = as.matrix(logcounts(current.sce))
      current.corr = cor(t(current.counts), method = "pearson")
      for (i in 1:nrow(current.corr)){
        current.corr[i,i] = 0
      }
      current.max_corr = max(max(current.corr))
      current.stat = data.frame(n_genes.selection = n_genes , corr_ratio = corr_ratio , max_corr = current.max_corr , n_genes = length(current.genes))
    }
    else {
      current.stat = data.frame(n_genes.selection = n_genes , corr_ratio = corr_ratio , max_corr = NA , n_genes = length(current.genes))
    }
    return(current.stat)
  })
  stat_per_n_genes = do.call(rbind , stat_per_n_genes)
  return(stat_per_n_genes)
})
stat_coexpression = do.call(rbind, stat_coexpression)

p1 = ggplot(stat_coexpression, aes(x = n_genes.selection , y = factor(corr_ratio) , fill = max_corr)) + 
  geom_tile(aes(fill = max_corr)) + 
  geom_text(aes(label = n_genes) , color = "red" , size = 5) +
  scale_fill_viridis(discrete = F) + 
  theme_classic() +
  labs(x = "# Genes selected" , y = "Gene score threshold") + 
  guides(fill=guide_legend(title="Max(corr)"))
p1
ggsave(filename = paste0(figures.dir, "lowly_explained_genes/" , "heatmap_stat" , ".png"), plot = p1, width = 4, height = 3)


```

# Session Info

```{r sessinf}
sessionInfo()
```
