---
title: "Pipeline to assess how addtionally selected genes improve cell type mapping (mouse embryo)."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
---

# Introduction & method


```{r load, message = FALSE}
# load libraries we are going to use

library(Matrix)
library(scran)
library(scater)
library(batchelor)
library(knitr)
library(reshape2)
library(edgeR)
library(ggplot2)
library(BiocSingular)
library(BiocParallel)
library(BiocNeighbors)
library(SingleCellExperiment)
library(dplyr)
library(BiocStyle)
library(stats)
#ncores = 5
#mcparam = MulticoreParam(workers = ncores)
#register(mcparam)
set.seed(32)

root.dir = "/Users/alsu/Develop/geneBasis/"
source(paste0(root.dir , "am_geneBasis/functions/main_functions.R"))
source(paste0(root.dir , "am_geneBasis/functions/visualization_functions.R"))

system = "atlas_E8.5"
figures.dir = paste0(root.dir , "figures/additional_selections/" , system, "/")
sce = readRDS(paste0(root.dir , "data/scRNA_datasets/" , system , "/sce_" , system , ".Rds"))

# reduce search - discard obviously uninteresting genes
sce = retain_only_hvgs(sce, n = 10000, var.thresh = 0)
  
# discard mitochondrial
rownames.sce = rowData(sce)[,2]
idx = which(!grepl("mt-" , rownames.sce) & !grepl("MT-" , rownames.sce) & !grepl("Mt-" , rownames.sce))
sce = sce[idx,]

# update cell types
celltype_legend_altered = c("Blood progenitors 1" = "Blood prog. 1" , "Blood progenitors 2" = "Blood prog. 2" , 
                            "Caudal Mesoderm" = "Caudal Mes." , "Forebrain/Midbrain/Hindbrain" = "Brain" , 
                            "Haematoendothelial progenitors" = "Haematoendo. prog." , 
                            "Intermediate mesoderm" = "Intermediate Mes." , "Pharyngeal mesoderm" = "Pharyngeal Mes." , 
                            "Somitic mesoderm" = "Somitic Mes.")
updated_celltypes = sapply(1:ncol(sce) , function(i){
  if (sce$celltype[i] %in% names(celltype_legend_altered)){
    return(as.character( celltype_legend_altered[which(names(celltype_legend_altered) == sce$celltype[i])] ) )
  }
  else {
    return(as.character( sce$celltype[i]) )
  }
})
sce$celltype = updated_celltypes


# define rare CTs
tab = as.data.frame( table(sce$celltype) )
colnames(tab) = c("celltype" , "n")
tab$frac = tab$n/sum(tab$n)

rare_CTs = as.character( tab$celltype[tab$n > 10 & tab$frac < 0.01] )
celltypes.2exclude = as.character(tab$celltype[tab$n < 10])



initial_selections = readRDS(paste0(root.dir , "data/additional_selections/" , system , "/initial_selections.Rds"))
additional_selections = readRDS(paste0(root.dir , "data/additional_selections/" , system , "/additional_selections.Rds"))
mappings = readRDS(paste0(root.dir , "data/additional_selections/" , system , "/mappings.Rds"))
  
k = 20



```

# Get CT order

```{r get-ct-order, message = FALSE}



get_ct_hierarchy = function(sce , batch = NULL, nPC = 50){
  hvgs_5000 = get_hvgs(sce , n = 5000)
  current.sce = sce[hvgs_5000, ]
  counts = as.matrix( logcounts(current.sce) )
  meta = as.data.frame(colData(sce))  
  if (is.null(batch)){
    pcs = irlba::prcomp_irlba(t(counts) , n = min(nPC, (nrow(counts)-1) , (ncol(counts) - 1)))
    counts = pcs$x
    rownames(counts) = colnames(current.sce)
  }
  else {
    batchFactor = factor(meta[, colnames(meta) == batch])
    counts = batchelor::multiBatchPCA(counts , batch = batchFactor , d = nPC)
    counts = do.call(batchelor::reducedMNN , counts)
    counts = counts$corrected
  }
  celltypes = unique(sce$celltype)      
  avg_pc_per_ct.stat = lapply(celltypes , function(celltype){
    cells = rownames(counts) %in% meta$cell[meta$celltype == celltype]
    return( apply( counts[cells,] , 2 , median))
  })
  avg_pc_per_ct.stat = do.call(cbind , avg_pc_per_ct.stat)
  colnames(avg_pc_per_ct.stat) = celltypes

  # build hierarchy
  dist = dist(t(avg_pc_per_ct.stat) , diag=TRUE)
  ct_hierarchy = hclust(dist ,  method = "ward.D2")
  out = celltypes[ ct_hierarchy$order ]
  return(out)
}

celltypes_ordered = get_ct_hierarchy(sce , batch = "sample", nPC = 20)
# manually rearrange for more consistent view
celltypes_ordered = replace(celltypes_ordered, c(2, 3), celltypes_ordered[c(3, 2)])
celltypes_ordered = replace(celltypes_ordered, c(5, 6), celltypes_ordered[c(6, 5)])




```

# Compare mappings

```{r compare-selections, message = FALSE}


# update mappings
updated_celltypes = sapply(1:nrow(mappings) , function(i){
  if (mappings$celltype[i] %in% names(celltype_legend_altered)){
    return(as.character( celltype_legend_altered[which(names(celltype_legend_altered) == mappings$celltype[i])] ) )
  }
  else {
    return(as.character( mappings$celltype[i]) )
  }
})
mappings$celltype = updated_celltypes


updated_celltypes = sapply(1:nrow(mappings) , function(i){
  if (mappings$mapped_celltype[i] %in% names(celltype_legend_altered)){
    return(as.character( celltype_legend_altered[which(names(celltype_legend_altered) == mappings$mapped_celltype[i])] ) )
  }
  else {
    return(as.character( mappings$mapped_celltype[i]) )
  }
})
mappings$mapped_celltype = updated_celltypes
  
  
                         
plots = lapply(c(4,20) , function(i){
  current.mapping = mappings[mappings$id == i , ]
  n_genes.begin = initial_selections[[i]]$n_genes
  n_genes.grid = c(n_genes.begin , n_genes.begin + 6 , n_genes.begin + 12)
  plots_per_id = lapply(n_genes.grid , function(n_genes){
    p = plot_mapping_heatmap(current.mapping[current.mapping$n_genes == n_genes & !current.mapping$celltype %in% celltypes.2exclude & !current.mapping$mapped_celltype %in% celltypes.2exclude,] , title = 
                               paste0(n_genes , " genes"), levels = celltypes_ordered ) + labs(x = "Cell type" , y = "Mapped cell type")
    return(p)
  })
  p = ggarrange(plotlist = plots_per_id, common.legend = T, ncol = 3) + theme(legend.position = "bottom")
  ggsave(filename = paste0(figures.dir, "mappings_",i ,".png"), plot = p, width = 18, height = 6)
  return(p)
})


```

#Session Info

```{r sessinf}
sessionInfo()
```
